owner: vaishnavvijay-prog
repo: zuro-status

sites:
  - name: Website
    url: https://getzuro.com
  - name: API
    url: https://getzuro.com/api/access

status-website:
  baseUrl: /zuro-status
  name: Zuro
